const ACTION_TYPES = {
  SET_CONTACTS: "SET_CONTACTS",
  ADD_CONTACT: "ADD_CONTACT",
  UPDATE_CONTACT: "UPDATE_CONTACT",
  DELETE_CONTACT: "DELETE_CONTACT",
  SET_CURRENT_CONTACT: "SET_CURRENT_CONTACT",
};

export default ACTION_TYPES;